version: '2.8'

services:
  # 1. DATABASE SERVICE
  db:
    image: postgis/postgis:16-3.4
    container_name: geoplant_db
    platform: linux/amd64
    shm_size: '2gb'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: geoplant
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./chelsa_raw:/raw_data
    ports:
      - "5432:5432"

  # 2. APP SERVICE (This was missing in your paste!)
  app:
    build: .
    container_name: geoplant_app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      # This tells Python where to find the database
      - DB_HOST=geoplant_db 
      - DB_USER=postgres
      - DB_PASS=admin
      - DB_NAME=geoplant

volumes:
  pg_data:
